spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rulesdb
    username: postgres
    password: admin1

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
